---
version: '3.4'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx_html:/usr/share/nginx/html
    depends_on:
      - sonarr
      - radarr
    restart: always

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "8090:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./sonarr:/config

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    ports:
      - "8100:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./radarr:/config
