- hosts: ans_host
  pre_tasks:
  - debug:
      msg: "{{ ansible_host }}"

  roles:
    - sql_rmine
    - web_rmine
  vars_files:
    - group_vars/main.yaml

  tasks:
    - name: "Add {{ app_fqdn }} to host file"
      shell: echo "127.0.0.1       {{ app_fqdn }}" >> /etc/hosts
      tags: 
        - test

    - name: Connectivity checks
      block:
        - uri:
            url: "http://{{ app_fqdn }}"
            return_content: yes
            timeout: 2
          register: this
          failed_when: "'Jean-Philippe Lang' not in this.content"
          tags: 
            - test
            - always
      rescue:
        - name: Send notification
          slack:
            token: TFBPBNB2L/B028ZLLM049/RVhRGjzXXaL1VaXwAjCuSGpR
            msg: 'Redmine web page is not running'
            channel: '#local-ansible'
            username: 'Ansible sender#' 
            icon_url: https://agardner.net/wp-content/uploads/2018/08/ansible-logo.png
            parse: 'full'

    - lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127.0.0.1       {{ app_fqdn }}'
      tags: 
        - test
        - always    
